name: Build

on:
    push:
        branches:
            - master
        tags:
            - 'v*'

    pull_request:

jobs:
    tests:
        uses: janpecha/actions/.github/workflows/nette-tester-project.yml@master
        with:
            phpVersions: '["8.2", "8.3"]'

    coding-style:
        uses: janpecha/actions/.github/workflows/code-checker.yml@master

    static-analysis:
        uses: janpecha/actions/.github/workflows/phpstan.yml@master
        with:
            phpVersions: '["8.2", "8.3"]'
